
postsubmits:
  - name: build-push-porch-gcp-controllers-dev-image
    cluster: default
    always_run: true
    branches:
    - "main"
    annotations:
      description: Build and Push Dev Image to DockerHub
    decorate: true
    decoration_config:
      censor_secrets: true
    max_concurrency: 1
    extra_refs:
    - org: nephio-project
      repo: porch-fleets
      base_ref: main
      path_alias: "porch_build"
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:debug
        command:
        - "/bin/sh"
        - "-c"
        - |
          executor --context=/home/prow/go/src/porch_build/ --dockerfile=controllers/Dockerfile --destination=nephio/porch-gcp-controllers:${PULL_BASE_REF} --destination=nephio/porch-gcp-controllers:latest
        volumeMounts:
          - name: kaniko-secret
            mountPath: /kaniko/.docker/
        resources:
          requests:
            cpu: 1
            memory: 1Gi
      volumes:
        - name: kaniko-secret
          secret:
            secretName: regcred
            items:
              - key: .dockerconfigjson
                path: config.json
